package pust.model.enumerations;

public enum Title {
    DISTRICTPOLICECOMMISSIONER,
    CHIEFSUPERINTENDENT,
    SUPERINTENDENT,
    INSPECTOR,
    ASSISTANT,
    ITADMINISTRATOR,
    ITCOORDINATOR
}
